const translation = {
    source: {
        text01: 'Yes',
        text02: 'No',
        text03: 'Next',
        text04: 'Do you like having sex with girls with big boobs?',
        text05: 'Find sexy women',
        text06: 'Important!',
        text07: 'Before we show you a list of women ready to have sex near you, we need to ask a few quick questions.',
        text08: "Women are used to having sex on this site. Maybe you'll meet someone you know...<br>Do you agree to keep the identity of the women on this site a secret?",
        text09: 'Have you ever had a sexual experience with strange girls with big boobs?',
        text10: "What is your friend's largest breast size?",
        text11: 'Thank you!',
        text12: 'We have selected for you women who live near you and want to have a good time, click more to see them',
    },
    en: {
        text01: 'Yes',
        text02: 'No',
        text03: 'Next',
        text04: 'Do you like having sex with girls with big boobs?',
        text05: 'Find sexy women',
        text06: 'Important!',
        text07: 'Before we show you a list of women ready to have sex near you, we need to ask a few quick questions.',
        text08: "Women are used to having sex on this site. Maybe you'll meet someone you know...<br>Do you agree to keep the identity of the women on this site a secret?",
        text09: 'Have you ever had a sexual experience with strange girls with big boobs?',
        text10: "What is your friend's largest breast size?",
        text11: 'Thank you!',
        text12: 'We have selected for you women who live near you and want to have a good time, click more to see them',
    },
    ar: {
        text01: 'نعم',
        text02: 'لا',
        text03: 'التالي',
        text04: 'هل تحب ممارسة الجنس مع الفتيات ذات الصدور الكبيرة؟',
        text05: 'العثور على نساء مثيرات',
        text06: 'مهم!',
        text07: 'قبل أن نعرض لك قائمة بالنساء المستعدات لممارسة الجنس بالقرب منك، نحتاج إلى طرح بعض الأسئلة السريعة.',
        text08: 'النساء معتادات على ممارسة الجنس على هذا الموقع. ربما ستلتقي بشخص تعرفه...<br> هل توافق على إبقاء هوية النساء في هذا الموقع سراً؟',
        text09: 'هل سبق لك أن قمت بتجربة جنسية مع فتيات غريبات ذوات أثداء كبيرة؟',
        text10: 'ما هو أكبر حجم صدر لدى صديقتك؟',
        text11: 'شكرًا لك!',
        text12: 'لقد اخترنا لك النساء اللاتي يعشن بالقرب منك ويرغبن في قضاء وقت ممتع، انقر فوق المزيد لرؤيتهن',
    },
    az: {
        text01: 'Bəli',
        text02: 'Xeyr',
        text03: 'Növbəti',
        text04: 'Böyük döşlü qızları sikməyi xoşlayırsan?',
        text05: 'Azğın qadınların tapılması',
        text06: 'Vacibdir!',
        text07: 'Sizə yaxınlıqdakı cinsi əlaqəyə hazır qadınların siyahısını göstərməzdən əvvəl bir neçə sürətli sual verməliyik.',
        text08: 'Qadınlar bu saytda seksə öyrəşiblər. Bəlkə tanıdığınız biri ilə tanış olarsınız...<br> Bu saytdakı qadınların kimliyini gizli saxlamağa razısınızmı?',
        text09: 'Heç böyük döşləri olan qəribə qızlarla cinsi əlaqədə olmusunuzmu?',
        text10: 'Sevgilinizin ən böyük döş ölçüsü nə idi?',
        text11: 'Təşəkkür edirəm!',
        text12: 'Sizin üçün yaxınlıqda yaşayan və əylənmək istəyən qadınları seçdik, onları görmək üçün daha sonra klikləyin',
    },
    cs: {
        text01: 'Ano',
        text02: 'Ne',
        text03: 'Další',
        text04: 'Rád šukáš dívky s velkými prsy?',
        text05: 'Finding Horny Women',
        text06: 'Důležité!',
        text07: 'Než vám ukážeme seznam žen připravených k sexu v okolí, musíme se zeptat na několik rychlých otázek.',
        text08: 'Ženy jsou na této stránce zvyklé na sex. Možná potkáte někoho, koho znáte...<br> Souhlasíte s tím, aby byla identita žen na této stránce utajena?',
        text09: 'Měl jsi někdy sexuální zkušenost s cizími dívkami s velkými prsy?',
        text10: 'Jaká byla největší velikost prsou, kterou měla vaše přítelkyně?',
        text11: 'Děkuji!',
        text12: 'Vybrali jsme pro vás ženy, které bydlí poblíž a chtějí se bavit, kliknutím dále je zobrazíte',
    },
    da: {
        text01: 'Ja',
        text02: 'Nej',
        text03: 'Næste',
        text04: 'Kan du lide at kneppe piger med store bryster?',
        text05: 'At finde liderlige kvinder',
        text06: 'Vigtigt!',
        text07: 'Før vi viser dig listen over parate til sex kvinder i nærheden, er vi nødt til at stille et par hurtige spørgsmål.',
        text08: 'Kvinder er vant til sex på denne side. Måske vil du møde en, du kender...<br> Er du enig i at holde identiteten på kvinderne på denne side hemmelig?',
        text09: 'Har du nogensinde haft seksuel oplevelse med fremmede piger med store bryster?',
        text10: 'Hvad var den største bryststørrelse, din kæreste havde?',
        text11: 'Tak!',
        text12: 'Vi har udvalgt til jer kvinder, der bor i nærheden og gerne vil have det sjovt, klik videre for at se dem',
    },
    de: {
        text01: 'Ja',
        text02: 'Nein',
        text03: 'Weiter',
        text04: 'Fickst du gerne Mädchen mit großen Brüsten?',
        text05: 'Geile Frauen finden',
        text06: 'Wichtig!',
        text07: 'Bevor wir Ihnen die Liste der sexbereiten Frauen in der Nähe zeigen, müssen wir ein paar kurze Fragen stellen.',
        text08: 'Frauen sind auf dieser Seite an Sex gewöhnt. Vielleicht triffst du jemanden, den du kennst...<br> Sind Sie damit einverstanden, die Identität der Frauen auf dieser Website geheim zu halten?',
        text09: 'Haben Sie jemals sexuelle Erfahrungen mit fremden Mädchen mit großen Brüsten gemacht?',
        text10: 'Was war die größte Brustgröße, die deine Freundin hatte?',
        text11: 'Danke!',
        text12: 'Wir haben für Sie Frauen ausgewählt, die in der Nähe wohnen und Spaß haben möchten. Klicken Sie weiter, um sie zu sehen',
    },
    el: {
        text01: 'Ναι',
        text02: 'Όχι',
        text03: 'Επόμενο',
        text04: 'Σας αρέσει να γαμάτε κορίτσια με μεγάλο στήθος;',
        text05: 'Βρίσκοντας καυλιάρες γυναίκες',
        text06: 'Σημαντικό!',
        text07: 'Προτού σας δείξουμε τη λίστα με τις έτοιμες για σεξ γυναίκες κοντά, πρέπει να κάνουμε μερικές γρήγορες ερωτήσεις.',
        text08: 'Οι γυναίκες έχουν συνηθίσει να κάνουν σεξ σε αυτόν τον ιστότοπο. Ίσως συναντήσετε κάποιον που γνωρίζετε...<br> Συμφωνείτε να κρατήσετε μυστική την ταυτότητα των γυναικών σε αυτόν τον ιστότοπο;',
        text09: 'Είχες ποτέ σεξουαλική εμπειρία με παράξενα κορίτσια με μεγάλο στήθος;',
        text10: 'Ποιο ήταν το μεγαλύτερο μέγεθος στήθους που είχε η κοπέλα σου;',
        text11: 'Ευχαριστώ!',
        text12: 'Επιλέξαμε για εσάς γυναίκες που μένουν κοντά και θέλουν να διασκεδάσουν, κάντε κλικ παρακάτω για να τις δείτε',
    },
    es: {
        text01: 'Sí',
        text02: 'No',
        text03: 'Siguiente',
        text04: '¿Te gusta follar con chicas con pechos grandes?',
        text05: 'Encontrar mujeres cachondas',
        text06: '¡Importante!',
        text07: 'Antes de mostrarte la lista de mujeres cercanas listas para tener sexo, debemos hacerte algunas preguntas rápidas.',
        text08: 'Las mujeres están acostumbradas al sexo en este sitio. Tal vez conozcas a alguien que conoces...<br> ¿Estás de acuerdo en mantener en secreto la identidad de las mujeres en este sitio?',
        text09: '¿Alguna vez has tenido experiencia sexual con chicas extrañas con pechos grandes?',
        text10: '¿Cuál era el tamaño de seno más grande que tenía tu novia?',
        text11: '¡Gracias!',
        text12: 'Hemos seleccionado para ti mujeres que viven cerca y quieren divertirse, haz clic más para verlas',
    },
    fa: {
        text01: 'بله',
        text02: 'نه',
        text03: 'بعدی',
        text04: 'دوست داری دخترهایی با سینه های بزرگ را فاک کنی؟',
        text05: 'در جستجوی زنان شاخدار',
        text06: 'مهم!',
        text07: 'قبل از اینکه لیستی از زنان آماده رابطه جنسی را در نزدیکی شما نشان دهیم، باید چند سوال سریع بپرسیم.',
        text08: 'زنان در این سایت به رابطه جنسی عادت دارند. شاید با کسی که می شناسید ملاقات کنید...<br> آیا موافقید که هویت زنان این سایت مخفی بماند؟',
        text09: 'آیا تا به حال تجربه جنسی با دختران عجیب و غریب با سینه های بزرگ داشته اید؟',
        text10: 'بزرگترین سایز سینه دوست دخترت چقدر بود؟',
        text11: 'ممنونم!',
        text12: 'ما برای شما زنانی که در این نزدیکی زندگی می کنید و می خواهید تفریح ​​کنید انتخاب کرده ایم، برای دیدن آنها روی ادامه مطلب کلیک کنید',
    },
    fr: {
        text01: 'Oui',
        text02: 'Non',
        text03: 'Suivant',
        text04: 'Tu aimes baiser des filles à gros seins ?',
        text05: 'Trouver des femmes excitées',
        text06: 'Important !',
        text07: "Avant de vous montrer la liste des femmes prêtes à faire l'amour à proximité, nous devons poser quelques questions rapides.",
        text08: "Les femmes sont habituées au sexe sur ce site. Peut-être rencontrerez-vous quelqu'un que vous connaissez...<br> Acceptez-vous de garder secrète l'identité des femmes présentes sur ce site ?",
        text09: 'Avez-vous déjà eu des relations sexuelles avec des filles étranges aux gros seins ?',
        text10: 'Quelle était la plus grande taille de poitrine de votre petite amie ?',
        text11: 'Merci !',
        text12: "Nous avons sélectionné pour vous des femmes qui habitent à proximité et qui souhaitent s'amuser, cliquez plus loin pour les voir",
    },
    hr: {
        text01: 'Da',
        text02: 'Ne',
        text03: 'Dalje',
        text04: 'Voliš li jebati cure s velikim grudima?',
        text05: 'Pronalaženje napaljenih žena',
        text06: 'Važno!',
        text07: 'Prije nego što vam pokažemo popis žena u blizini spremnih za seks, moramo postaviti nekoliko brzih pitanja.',
        text08: 'Žene su navikle na seks na ovoj stranici. Možda ćete upoznati nekoga koga poznajete...<br> Slažete li se da identitet žena na ovoj stranici ostane tajna?',
        text09: 'Jeste li ikada imali seksualno iskustvo sa nepoznatim djevojkama s velikim grudima?',
        text10: 'Koju je najveću veličinu grudi imala vaša djevojka?',
        text11: 'Hvala!',
        text12: 'Odabrali smo za vas žene koje žive u blizini i žele se zabaviti, kliknite dalje da ih vidite',
    },
    hu: {
        text01: 'Igen',
        text02: 'Nem',
        text03: 'Következő',
        text04: 'Szeretsz nagy mellű lányokat dugni?',
        text05: 'Kányos nők keresése',
        text06: 'Fontos!',
        text07: 'Mielőtt megmutatnánk a közelben lévő, szexre kész nők listáját, fel kell tennünk néhány gyors kérdést.',
        text08: 'A nők hozzászoktak a szexhez ezen az oldalon. Talán találkozik valakivel, akit ismer...<br> Beleegyezik, hogy titokban tartsa az ezen az oldalon szereplő nők kilétét?',
        text09: 'Volt már szexuális élményed idegen, nagy mellű lányokkal?',
        text10: 'Mekkora volt a barátnőd legnagyobb mellmérete?',
        text11: 'Köszönöm!',
        text12: 'Kiválasztottunk neked olyan nőket, akik a közelben élnek, és szórakozni szeretnének, kattints tovább a megtekintéséhez',
    },
    id: {
        text01: 'Ya',
        text02: 'Tidak',
        text03: 'Selanjutnya',
        text04: 'Apakah kamu suka meniduri gadis berpayudara besar?',
        text05: 'Menemukan Wanita Terangsang',
        text06: 'Penting!',
        text07: 'Sebelum kami menampilkan daftar wanita siap berhubungan seks terdekat, kami perlu mengajukan beberapa pertanyaan singkat.',
        text08: 'Wanita terbiasa berhubungan seks di situs ini. Mungkin Anda akan bertemu dengan seseorang yang Anda kenal...<br> Apakah Anda setuju untuk merahasiakan identitas wanita di situs ini?',
        text09: 'Apakah kamu pernah mempunyai pengalaman seksual dengan gadis aneh yang berpayudara besar?',
        text10: 'Berapa ukuran payudara terbesar yang dimiliki pacarmu?',
        text11: 'Terima kasih!',
        text12: 'Kami telah memilihkan untuk Anda para wanita yang tinggal di sekitar dan ingin bersenang-senang, klik lebih lanjut untuk melihat mereka',
    },
    it: {
        text01: 'Sì',
        text02: 'No',
        text03: 'Avanti',
        text04: 'Ti piace scopare ragazze con il seno grande?',
        text05: 'Trovare donne arrapate',
        text06: 'Importante!',
        text07: "Prima di mostrarti l'elenco delle donne pronte per fare sesso nelle vicinanze, dobbiamo farti alcune domande veloci.",
        text08: "Le donne sono abituate al sesso su questo sito. Forse incontrerai qualcuno che conosci...<br> Accetti di mantenere segreta l'identità delle donne su questo sito?",
        text09: 'Hai mai avuto esperienze sessuali con strane ragazze dal seno grande?',
        text10: 'Qual era la dimensione del seno più grande che aveva la tua ragazza?',
        text11: 'Grazie!',
        text12: 'Abbiamo selezionato per te donne che vivono nelle vicinanze e vogliono divertirsi, clicca più avanti per vederle',
    },
    ja: {
        text01: 'はい',
        text02: 'いいえ',
        text03: '次へ',
        text04: '大きな胸の女の子とセックスするのは好きですか?',
        text05: 'エッチな女性を見つける',
        text06: '重要!',
        text07: '近くにいるすぐにセックスできる女性のリストを表示する前に、いくつか簡単な質問をする必要があります。',
        text08: '女性はこのサイトでのセックスに慣れています。もしかしたら、知り合いに会えるかもしれません...<br> このサイトの女性の身元を秘密にすることに同意しますか?',
        text09: '大きな胸を持つ見知らぬ女の子と性的経験をしたことがありますか?',
        text10: 'あなたのガールフレンドの最大の胸のサイズはどれくらいですか?',
        text11: 'ありがとう!',
        text12: '近くに住んでいて楽しみたい女性を厳選しました。さらにクリックして見てください',
    },
    nl: {
        text01: 'Ja',
        text02: 'Nee',
        text03: 'Volgende',
        text04: 'Hou je ervan om meisjes met grote borsten te neuken?',
        text05: 'Geile vrouwen vinden',
        text06: 'Belangrijk!',
        text07: 'Voordat we je de lijst laten zien met vrouwen die klaar zijn voor seks in de buurt, moeten we een paar korte vragen stellen.',
        text08: 'Vrouwen zijn gewend aan seks op deze site. Misschien ontmoet je iemand die je kent...<br> Gaat u ermee akkoord de identiteit van de vrouwen op deze site geheim te houden?',
        text09: 'Heb je ooit seksuele ervaring gehad met vreemde meisjes met grote borsten?',
        text10: 'Wat was de grootste borstomvang die je vriendin had?',
        text11: 'Bedankt!',
        text12: 'We hebben voor u vrouwen geselecteerd die in de buurt wonen en plezier willen hebben, klik verder om ze te zien',
    },
    pl: {
        text01: 'Tak',
        text02: 'Nie',
        text03: 'Dalej',
        text04: 'Czy lubisz ruchać dziewczyny z dużymi piersiami?',
        text05: 'Znajdowanie napalonych kobiet',
        text06: 'Ważne!',
        text07: 'Zanim pokażemy Ci listę kobiet gotowych do seksu w pobliżu, musimy zadać kilka krótkich pytań.',
        text08: 'Kobiety są przyzwyczajone do seksu na tej stronie. Może spotkasz kogoś, kogo znasz...<br> Czy zgadzasz się zachować w tajemnicy tożsamość kobiet znajdujących się na tej stronie?',
        text09: 'Czy kiedykolwiek miałeś doświadczenia seksualne z dziwnymi dziewczynami z dużymi piersiami?',
        text10: 'Jaki był największy rozmiar piersi Twojej dziewczyny?',
        text11: 'Dziękuję!',
        text12: 'Wybraliśmy dla Ciebie kobiety, które mieszkają w pobliżu i chcą się zabawić, kliknij dalej, aby je zobaczyć',
    },
    pt: {
        text01: 'Sim',
        text02: 'Não',
        text03: 'Próximo',
        text04: 'Você gosta de foder garotas com seios grandes?',
        text05: 'Encontrando mulheres com tesão',
        text06: 'Importante!',
        text07: 'Antes de mostrarmos a lista de mulheres prontas para fazer sexo nas proximidades, precisamos fazer algumas perguntas rápidas.',
        text08: 'As mulheres estão acostumadas com sexo neste site. Talvez você conheça alguém que você conhece...<br> Você concorda em manter em segredo a identidade das mulheres deste site?',
        text09: 'Você já teve experiência sexual com garotas estranhas com seios grandes?',
        text10: 'Qual foi o maior tamanho de peito que sua namorada teve?',
        text11: 'Obrigado!',
        text12: 'Selecionamos para vocês mulheres que moram perto e querem se divertir, clique mais para vê-las',
    },
    ro: {
        text01: 'Da',
        text02: 'Nu',
        text03: 'Următorul',
        text04: 'Îți place să tragi fete cu sânii mari?',
        text05: 'Găsirea femeilor excitate',
        text06: 'Important!',
        text07: 'Înainte de a vă arăta lista de femei gata de sex din apropiere, trebuie să punem câteva întrebări rapide.',
        text08: 'Femeile sunt obișnuite să facă sex pe acest site. Poate vei întâlni pe cineva cunoscut...<br> Sunteți de acord să păstrați secretă identitatea femeilor de pe acest site?',
        text09: 'Ai avut vreodată experiență sexuală cu fete ciudate, cu sânii mari?',
        text10: 'Care a fost cea mai mare dimensiune a sânilor pe care a avut-o prietena ta?',
        text11: 'Mulțumesc!',
        text12: 'Am selectat pentru tine femei care locuiesc în apropiere și vor să se distreze, dă clic mai departe pentru a le vedea',
    },
    ru: {
        text01: 'Да',
        text02: 'Нет',
        text03: 'Далее',
        text04: 'Нравится трахать девушек с большим бюстом?',
        text05: 'Поиск возбужденных женщин',
        text06: 'Важно!',
        text07: 'Перед тем, как мы покажем тебе список готовых к сексу находящихся рядом женщин, нам нужно быстро задать несколько вопросов.',
        text08: 'На этом сайте женщины привыкли к сексу. Возможно, вы встретите кого-то из своих знакомых... Согласны ли вы хранить в тайне личность женщин на этом сайте?',
        text09: 'У вас уже был сексуальный опыт с незнакомыми девушками с большим бюстом?',
        text10: 'Какой наибольший размер груди был у твоей девушки?',
        text11: 'Спасибо!',
        text12: 'Мы подобрали тебе женщин, живущих рядом, и хотят развлечься, кликай дальше, чтобы увидеть их',
    },
    sr: {
        text01: 'Да',
        text02: 'Не',
        text03: 'Следеће',
        text04: 'Да ли волиш да јебеш девојке са великим грудима?',
        text05: 'Проналажење напаљених жена',
        text06: 'Важно!',
        text07: 'Пре него што вам покажемо листу жена спремних за секс у близини, морамо да поставимо неколико брзих питања.',
        text08: 'Жене су навикле на секс на овом сајту. Можда ћете упознати некога кога познајете...<br> Да ли се слажете да идентитет жена на овом сајту остане тајна?',
        text09: 'Да ли сте икада имали сексуално искуство са чудним девојкама са великим грудима?',
        text10: 'Коју је највећу груди имала твоја девојка?',
        text11: 'Хвала!',
        text12: 'Изабрали смо за вас жене које живе у близини и желе да се забаве, кликните даље да их видите',
    },
    sv: {
        text01: 'Ja',
        text02: 'Nej',
        text03: 'Nästa',
        text04: 'Tycker du om att knulla tjejer med stora bröst?',
        text05: 'Hitta kåta kvinnor',
        text06: 'Viktigt!',
        text07: 'Innan vi visar dig listan över kvinnor som är redo att ha sex i närheten måste vi ställa några snabba frågor.',
        text08: 'Kvinnor är vana vid sex på den här sidan. Kanske kommer du att träffa någon du känner...<br> Går du med på att hålla identiteten på kvinnorna på den här sidan hemlig?',
        text09: 'Har du någonsin haft sexuell erfarenhet av främmande tjejer med stora bröst?',
        text10: 'Vilken var den största bröststorleken din flickvän hade?',
        text11: 'Tack!',
        text12: 'Vi har valt ut för er kvinnor som bor i närheten och vill ha kul, klicka vidare för att se dem',
    },
    th: {
        text01: 'ใช่',
        text02: 'ไม่',
        text03: 'ถัดไป',
        text04: 'คุณชอบเย็ดสาวหน้าอกใหญ่ไหม',
        text05: 'ค้นหาผู้หญิงเงี่ยน',
        text06: 'สำคัญ!',
        text07: 'ก่อนที่เราจะแสดงรายชื่อผู้หญิงที่พร้อมมีเพศสัมพันธ์ในบริเวณใกล้เคียง เราต้องถามคำถามสั้นๆ สองสามข้อก่อน',
        text08: 'ผู้หญิงเคยชินกับการมีเซ็กส์บนเว็บไซต์นี้ บางทีคุณอาจได้พบกับคนที่คุณรู้จัก...<br> คุณตกลงที่จะเก็บข้อมูลระบุตัวตนของผู้หญิงบนเว็บไซต์นี้ไว้เป็นความลับหรือไม่',
        text09: 'คุณเคยมีประสบการณ์ทางเพศกับผู้หญิงแปลกหน้าที่มีหน้าอกใหญ่บ้างไหม',
        text10: 'ขนาดหน้าอกที่ใหญ่ที่สุดที่แฟนของคุณมีคือเท่าไร',
        text11: 'ขอบคุณ!',
        text12: 'เราได้เลือกผู้หญิงที่อาศัยอยู่ใกล้ ๆ และต้องการความสนุกสนาน คลิกเพิ่มเติมเพื่อดูพวกเขา',
    },
    tr: {
        text01: 'Evet',
        text02: 'Hayır',
        text03: 'Sonraki',
        text04: 'Büyük göğüslü kızları sikmeyi sever misin?',
        text05: 'Azgın Kadınları Bulma',
        text06: 'Önemli!',
        text07: 'Size yakınınızdaki sekse hazır kadınların listesini göstermeden önce birkaç kısa soru sormamız gerekiyor.',
        text08: 'Kadınlar bu sitede seks yapmaya alışkın. Belki tanıdığınız biriyle tanışırsınız...<br> Bu sitedeki kadınların kimliğinin gizli tutulmasını kabul ediyor musunuz?',
        text09: 'Hiç büyük göğüslü garip kızlarla cinsel deneyiminiz oldu mu?',
        text10: 'Kız arkadaşınızın en büyük göğüs ölçüsü neydi?',
        text11: 'Teşekkür ederim!',
        text12: 'Sizler için yakınlarda yaşayan ve eğlenmek isteyen kadınları seçtik, görmek için devamına tıklayın',
    },
    uk: {
        text01: 'Так',
        text02: 'Ні',
        text03: 'Далі',
        text04: 'Подобається трахати дівчат з великим бюстом?',
        text05: 'Пошук збуджених жінок',
        text06: 'Важливо!',
        text07: 'Перед тим, як ми покажемо тобі список готових до сексу жінок, що знаходяться поруч, нам потрібно швидко поставити кілька питань.',
        text08: 'На цьому сайті жінки звикли до сексу. Можливо, ви зустрінете когось із своїх знайомих...<br> Чи згодні ви зберігати в таємниці особистість жінок на цьому сайті?',
        text09: 'У вас уже був сексуальний досвід із незнайомими дівчатами з великим бюстом?',
        text10: 'Який найбільший розмір грудей був у твоєї дівчини?',
        text11: 'Дякую!',
        text12: 'Ми підібрали тобі жінок, що живуть поруч, та хочуть розважитись, клікай далі щоб побачити їх',
    },
    vi: {
        text01: 'Có',
        text02: 'Không',
        text03: 'Tiếp theo',
        text04: 'Bạn có thích đụ những cô gái ngực to không?',
        text05: 'Tìm phụ nữ hứng tình',
        text06: 'Quan trọng!',
        text07: 'Trước khi cho bạn xem danh sách những phụ nữ sẵn sàng quan hệ tình dục ở gần đây, chúng tôi cần hỏi một vài câu hỏi nhanh.',
        text08: 'Phụ nữ đã quen với việc quan hệ tình dục trên trang này. Có thể bạn sẽ gặp một người nào đó mà bạn biết...<br> Bạn có đồng ý giữ bí mật danh tính của những người phụ nữ trên trang này không?',
        text09: 'Bạn đã từng quan hệ tình dục với những cô gái lạ có bộ ngực khủng chưa?',
        text10: 'Bộ ngực lớn nhất mà bạn gái bạn có là bao nhiêu?',
        text11: 'Cảm ơn bạn!',
        text12: 'Chúng tôi đã chọn cho bạn những phụ nữ sống gần đó và muốn vui chơi, hãy nhấp vào thêm để xem họ',
    },
    zh: {
        text01: '是',
        text02: '不',
        text03: '下一个',
        text04: '你喜欢操大胸女孩吗？',
        text05: '寻找饥渴的女人',
        text06: '重要！',
        text07: '在我们向您展示附近准备性行为的女性名单之前，我们需要问几个简单的问题。',
        text08: '女性习惯在这个网站上做爱。也许您会遇到您认识的人...<br>您同意对本网站上的女性身份保密吗？',
        text09: '你有过和陌生巨乳女孩发生性关系的经历吗？',
        text10: '你女朋友最大的胸部尺寸是多少？',
        text11: '谢谢！',
        text12: '我们为您挑选了住在附近、想玩得开心的女性，进一步点击查看她们',
    },
};

function detect_language() {
    var userLang =
        (navigator.languages && navigator.languages[0]) ||
        navigator.language ||
        navigator.userLanguage;

    if (userLang == 'zh-CN' || userLang == 'zh-SG' || userLang == 'zh-MY' || userLang == 'zh-CHS') {
        userLang = 'zh';
    } else if (
        userLang == 'zh-HK' ||
        userLang == 'zh-MO' ||
        userLang == 'zh-TW' ||
        userLang == 'zh-CHT'
    ) {
        userLang = 'zh';
    } else if (userLang.length > 2) {
        userLang = userLang[0] + userLang[1];
    }

    return userLang;
}

document.addEventListener('DOMContentLoaded', function (event) {
    let browserLang = detect_language();
    const langTranslation =
        translation[browserLang] && Object.keys(translation[browserLang]).length > 0
            ? translation[browserLang]
            : translation['source'];

    for (const textKey of Object.keys(langTranslation)) {
        const textString = langTranslation[textKey];
        if (textKey === 'title') {
            $(textKey).text(textString);
        } else {
            $(`.${textKey}`).html(textString);
        }
    }
});
